version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ginblog_db
    environment:
      MYSQL_ROOT_PASSWORD: wwy040609
      MYSQL_DATABASE: NewGinBlog
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: ginblog_app
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - APP_MODE=${APP_MODE}
      - HTTP_PORT=${HTTP_PORT}
      - JWT_KEY=${JWT_KEY}
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

volumes:
  db_data: